version: "3"

services: 
  quadbot:
    image: quadbot:latest
    container_name: quadbot-docker
    # You can enable testing by setting QUADBOT_TESTING to some value
    # Place Discord token here
    env_file: .env
    volumes:
      - .:/quadbot
